/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.example.sqliteviewer;

import javax.swing.*;

public class ApplicationRunner {
    public static void main(String[] args) {
        SwingUtilities.invokeLater(SQLiteViewer::new);
    }
}
